import { useMemo, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../utils/dataLoader';
import { PageHeader, ArchiveNotice } from '../components/shared/ArchiveUI';
import { useAuth } from '../hooks/useAuth';
import { useConcordanceLedger } from '../hooks/useConcordanceLedger';
import { ACTION_LABELS, STATE_LABELS, deriveRelationState, relationActions, type ConcordanceActionKind, type ConcordanceDisplayState } from '../utils/concordanceLedger';
import type { AnalyticalConfidence, Relation, RelationType } from '../types';

function labelFor(id: string) { return api.getEntityById(id)?.nome || api.getRecordById(id)?.titolo || id; }
function linkFor(id: string) { return api.getEntityById(id) ? `/segreta/entita/${id}` : api.getRecordById(id) ? `/segreta/record/${id}` : '#'; }
const relationTypeLabels: Record<string, string> = { possible_match:'corrispondenza possibile', collegato_a:'collegato a', associato_a:'associato a', avvenuto_a:'avvenuto a', osservato_in:'osservato in', precede:'precede', contraddice:'contraddice', presente_a:'presente a', membro_di:'membro di', menzionato_in:'menzionato in', custodito_da:'custodito da', prodotto_da:'prodotto da' };
const relationTypes = Object.entries(relationTypeLabels) as [RelationType, string][];
const actionChoices: {value:ConcordanceActionKind; label:string}[] = [
  {value:'plausible',label:'Valutare come plausibile'}, {value:'support',label:'Aggiungere un riscontro favorevole'},
  {value:'contest',label:'Contestare la concordanza'}, {value:'contradict',label:'Registrare una contraddizione'},
  {value:'insufficient',label:'Dichiarare gli elementi insufficienti'}, {value:'discard',label:'Scartare per errore materiale'},
];

function stateTone(state: ConcordanceDisplayState) { return ['contradicted','discarded','contested','validated_contested','confirmed_contested'].includes(state) ? 'alert' : ['confirmed','locally_validated'].includes(state) ? 'confirmed' : 'pending'; }

export function Concordanze() {
  const { user } = useAuth(); const { ledger, loading, error, propose } = useConcordanceLedger(); const [proposalOpen,setProposalOpen]=useState(false);
  const relations=[...api.getRelations(),...ledger.proposals];
  const states=relations.map(relation=>deriveRelationState(relation,ledger).state);
  const validated=states.filter(state=>state==='confirmed'||state==='locally_validated'||state==='confirmed_contested'||state==='validated_contested').length;
  const pending=states.filter(state=>state==='unvalidated'||state==='plausible'||state==='insufficient').length;
  const contested=states.filter(state=>state==='contested'||state==='contradicted'||state==='validated_contested'||state==='confirmed_contested').length;
  return <div className="page-standard"><PageHeader eyebrow="ANALISI DELLE RELAZIONI" title="Concordanze" meta="PROPOSTE, RISCONTRI E REVISIONI LOCALI" actions={<button className="archive-action" disabled={!user} onClick={()=>setProposalOpen(true)}>PROPORRE CONCORDANZA</button>}/>
    {!user&&<ArchiveNotice tone="warning">Autenticare il Testimone di Tavola per proporre o valutare concordanze.</ArchiveNotice>}
    {error&&<ArchiveNotice tone="warning">{error}. Avviare INDICE attraverso il servizio locale per registrare decisioni.</ArchiveNotice>}
    <div className="metrics-bar compact"><div className="metric-box"><span className="metric-label">CONVALIDATE</span><span className="metric-value">{validated}</span></div><div className="metric-box"><span className="metric-label">IN ESAME</span><span className="metric-value highlight">{pending}</span></div><div className="metric-box"><span className="metric-label">CONTESTATE</span><span className="metric-value alert">{contested}</span></div></div>
    <div className="feature-grid"><Link className="feature-panel" to="/concordanze/grafo"><span>01 / TOPOLOGIA</span><h2>Esplora il grafo</h2><p>Entità e relazioni note nel nodo locale.</p></Link><Link className="feature-panel" to="/concordanze/corrispondenze"><span>02 / REVISIONE</span><h2>Valuta le concordanze</h2><p>Registra riscontri, dissensi e contraddizioni.</p></Link><Link className="feature-panel" to="/concordanze/cronologia"><span>03 / TEMPO</span><h2>Cronologia comparata</h2><p>Eventi e record ordinati per data.</p></Link></div>
    <section className="panel"><header className="panel-header"><h2>RELAZIONI RECENTI</h2></header><div className="relation-list padded">{loading?<div className="empty-state">LETTURA DEL REGISTRO...</div>:relations.slice(-8).reverse().map(r=><RelationRow key={r.id} relation={r} state={deriveRelationState(r,ledger).state}/>)}</div></section>
    {proposalOpen&&user&&<ProposalModal segnaposto={user.identificativo} onClose={()=>setProposalOpen(false)} onSubmit={async input=>{await propose(input);setProposalOpen(false);}}/>}
  </div>;
}

function RelationRow({relation:r,state}:{relation:Relation;state:ConcordanceDisplayState}) { return <div className="relation-row relation-full"><span className={`relation-mark relation-${stateTone(state)}`}></span><Link to={linkFor(r.from)}>{labelFor(r.from)}</Link><span className="relation-type">{relationTypeLabels[r.tipo] || r.tipo.replace(/_/g,' ')}</span><Link to={linkFor(r.to)}>{labelFor(r.to)}</Link><small>{STATE_LABELS[state]}</small></div> }

export function ConcordanceGraph(){
  const {ledger}=useConcordanceLedger(); const relations=[...api.getRelations(),...ledger.proposals].filter(r=>api.getEntityById(r.from)&&api.getEntityById(r.to)); const ids=[...new Set(relations.flatMap(r=>[r.from,r.to]))]; const [selected,setSelected]=useState(ids[0]||'');
  const positions=useMemo(()=>Object.fromEntries(ids.map((id,i)=>[id,{x:50+40*Math.cos(i/ids.length*Math.PI*2),y:50+40*Math.sin(i/ids.length*Math.PI*2)}])),[ids]);
  const connected=relations.filter(r=>r.from===selected||r.to===selected);
  return <div className="page-standard"><PageHeader eyebrow="CONCORDANZE" title="Grafo delle relazioni" meta={`${ids.length} NODI · ${relations.length} ARCHI · SELEZIONA UN NODO`}/><div className="graph-layout"><div className="graph-canvas"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Grafo delle relazioni">{relations.map(r=><line key={r.id} x1={positions[r.from].x} y1={positions[r.from].y} x2={positions[r.to].x} y2={positions[r.to].y} className={`edge edge-${stateTone(deriveRelationState(r,ledger).state)}`}/>)}</svg>{ids.map(id=>{const bits=id.split('-');return <button key={id} style={{left:`${positions[id].x}%`,top:`${positions[id].y}%`}} className={`graph-node ${selected===id?'selected':''}`} onClick={()=>setSelected(id)} title={labelFor(id)}><span>{bits[1]}</span><small>{bits[bits.length-1]}</small></button>})}</div><aside className="graph-inspector"><div className="section-kicker">NODO SELEZIONATO</div><h2>{labelFor(selected)}</h2><code>{selected}</code><div className="relation-list">{connected.map(r=><RelationRow key={r.id} relation={r} state={deriveRelationState(r,ledger).state}/>)}</div></aside></div></div>
}

export function Matches(){
  const {user}=useAuth(); const {ledger,loading,error,recordAction}=useConcordanceLedger(); const [selected,setSelected]=useState<Relation|null>(null); const rows=[...api.getRelations(),...ledger.proposals];
  return <div className="page-standard"><PageHeader eyebrow="CONCORDANZE" title="Valutazione delle concordanze" meta="OGNI DECISIONE RESTA ATTRIBUITA AL SEGNAPOSTO"/>{error&&<ArchiveNotice tone="warning">{error}</ArchiveNotice>}{loading?<div className="empty-state">LETTURA DEL REGISTRO...</div>:<div className="assessment-list">{rows.map(r=>{const derived=deriveRelationState(r,ledger);const history=relationActions(r.id,ledger);return <article key={r.id} className={`match-card match-${stateTone(derived.state)}`}><div className="match-code">{r.id} · {STATE_LABELS[derived.state].toUpperCase()}</div><h2><Link to={linkFor(r.from)}>{labelFor(r.from)}</Link><span>↔</span><Link to={linkFor(r.to)}>{labelFor(r.to)}</Link></h2><div className="match-relation-type">{relationTypeLabels[r.tipo]||r.tipo.replace(/_/g,' ')}</div><p>{r.reason||'Relazione registrata nei dati locali.'}</p><footer>{r.supportedBy?.length?`Supporti originari: ${r.supportedBy.join(', ')}`:`Rilevata: ${r.dataRilevazione||'data non indicata'}`}</footer><div className="concordance-summary"><span>FAVOREVOLI <strong>{derived.favorable}</strong></span><span>DISSENSI <strong>{derived.contested}</strong></span><span>ATTI <strong>{history.length}</strong></span></div>{history.length>0&&<details className="decision-history"><summary>CRONOLOGIA DELLE VALUTAZIONI</summary>{history.map(action=><div className="decision-entry" key={action.id}><div><strong>{ACTION_LABELS[action.action]}</strong><span>{action.segnaposto} · {action.recordedAt}</span></div><p>{action.reason}</p>{action.supportIds.length>0&&<small>Supporti: {action.supportIds.join(', ')}</small>}</div>)}</details>}<button className="archive-action secondary" disabled={!user} onClick={()=>setSelected(r)}>{user?'REGISTRA VALUTAZIONE':'AUTENTICAZIONE RICHIESTA'}</button></article>})}</div>}{selected&&user&&<ActionModal relation={selected} state={deriveRelationState(selected,ledger).state} segnaposto={user.identificativo} onClose={()=>setSelected(null)} onSubmit={async input=>{await recordAction(input);setSelected(null);}}/>}</div>
}

function SupportSelector({selected,onChange}:{selected:string[];onChange:(ids:string[])=>void}) { const records=api.getRecords();return <fieldset className="support-selector"><legend>RECORD DI SUPPORTO O CONTRARI</legend>{records.map(record=><label key={record.id}><input type="checkbox" checked={selected.includes(record.id)} onChange={event=>onChange(event.target.checked?[...selected,record.id]:selected.filter(id=>id!==record.id))}/><span><strong>{record.id}</strong>{record.titolo}</span></label>)}</fieldset> }

function ProposalModal({segnaposto,onClose,onSubmit}:{segnaposto:string;onClose:()=>void;onSubmit:(input:{from:string;to:string;tipo:RelationType;reason:string;supportIds:string[];segnaposto:string})=>Promise<void>}) { const entities=api.getEntities();const [from,setFrom]=useState(entities[0]?.id||'');const [to,setTo]=useState(entities[1]?.id||'');const [tipo,setTipo]=useState<RelationType>('collegato_a');const [reason,setReason]=useState('');const [supportIds,setSupportIds]=useState<string[]>([]);const [saving,setSaving]=useState(false);const [error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();if(from===to){setError('Selezionare due entità differenti.');return;}setSaving(true);try{await onSubmit({from,to,tipo,reason,supportIds,segnaposto});}catch(e){setError(e instanceof Error?e.message:'Registrazione non riuscita');setSaving(false);}}return <div className="concordance-modal-backdrop" onClick={onClose}><form className="concordance-modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><header><div><span>CONCORDANZE / NUOVA PROPOSTA</span><h2>Proporre una concordanza</h2></div><button type="button" onClick={onClose}>×</button></header><div className="concordance-form"><div className="form-pair"><label>PRIMA ENTITÀ<select value={from} onChange={e=>setFrom(e.target.value)}>{entities.map(entity=><option key={entity.id} value={entity.id}>{entity.id} · {entity.nome}</option>)}</select></label><label>SECONDA ENTITÀ<select value={to} onChange={e=>setTo(e.target.value)}>{entities.map(entity=><option key={entity.id} value={entity.id}>{entity.id} · {entity.nome}</option>)}</select></label></div><label>TIPO DI RELAZIONE<select value={tipo} onChange={e=>setTipo(e.target.value as RelationType)}>{relationTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>MOTIVAZIONE<textarea required minLength={12} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Descrivere perché la relazione merita di essere esaminata."/></label><SupportSelector selected={supportIds} onChange={setSupportIds}/>{error&&<p className="form-error">{error}</p>}<div className="form-attestation">REGISTRANTE · {segnaposto.toUpperCase()} · NODO SAL</div><div className="form-actions"><button type="button" onClick={onClose}>ANNULLA</button><button className="archive-action" disabled={saving}>{saving?'REGISTRAZIONE...':'REGISTRA PROPOSTA'}</button></div></div></form></div> }

function ActionModal({relation,state,segnaposto,onClose,onSubmit}:{relation:Relation;state:ConcordanceDisplayState;segnaposto:string;onClose:()=>void;onSubmit:(input:{relationId:string;action:ConcordanceActionKind;reason:string;confidence:AnalyticalConfidence;supportIds:string[];segnaposto:string})=>Promise<void>}) { const [action,setAction]=useState<ConcordanceActionKind>('plausible');const [reason,setReason]=useState('');const [confidence,setConfidence]=useState<AnalyticalConfidence>('bassa');const [supportIds,setSupportIds]=useState<string[]>([]);const [saving,setSaving]=useState(false);const [error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();setSaving(true);try{await onSubmit({relationId:relation.id,action,reason,confidence,supportIds,segnaposto});}catch(e){setError(e instanceof Error?e.message:'Registrazione non riuscita');setSaving(false);}}return <div className="concordance-modal-backdrop" onClick={onClose}><form className="concordance-modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><header><div><span>{relation.id} · STATO: {STATE_LABELS[state]}</span><h2>Registrare una valutazione</h2></div><button type="button" onClick={onClose}>×</button></header><div className="concordance-form"><div className="relation-under-review"><strong>{labelFor(relation.from)}</strong><span>{relationTypeLabels[relation.tipo]||relation.tipo}</span><strong>{labelFor(relation.to)}</strong></div><div className="form-pair"><label>ESITO<select value={action} onChange={e=>setAction(e.target.value as ConcordanceActionKind)}>{actionChoices.map(choice=><option key={choice.value} value={choice.value}>{choice.label}</option>)}</select></label><label>CONFIDENZA ANALITICA<select value={confidence} onChange={e=>setConfidence(e.target.value as AnalyticalConfidence)}><option value="bassa">Bassa</option><option value="moderata">Moderata</option><option value="alta">Alta</option></select></label></div><label>MOTIVAZIONE<textarea required minLength={12} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Esplicitare il ragionamento e i limiti della valutazione."/></label><SupportSelector selected={supportIds} onChange={setSupportIds}/>{error&&<p className="form-error">{error}</p>}<div className="form-attestation">ATTO ATTRIBUITO A · {segnaposto.toUpperCase()} · NODO SAL</div><div className="form-actions"><button type="button" onClick={onClose}>ANNULLA</button><button className="archive-action" disabled={saving}>{saving?'REGISTRAZIONE...':'REGISTRA NELLA CONCORDANZA'}</button></div></div></form></div> }

export function Timeline(){const entities=api.getEntities().filter(e=>e.tipo==='evento').map(e=>({id:e.id,title:e.nome,date:(e as {data?:string}).data||e.periodoInizio||'',kind:'Evento'}));const records=api.getRecords().map(r=>({id:r.id,title:r.titolo,date:r.dataOriginale||r.dataAcquisizione,kind:'Record'}));const items=[...entities,...records].sort((a,b)=>a.date.localeCompare(b.date));return <div className="page-standard"><PageHeader eyebrow="CONCORDANZE" title="Cronologia comparata" meta={`${items.length} OCCORRENZE DATATE`}/><div className="timeline">{items.map(i=><div className="timeline-row" key={`${i.kind}-${i.id}`}><div className="timeline-date">{i.date}</div><div className="timeline-track"><span></span></div><div><small>{i.kind.toUpperCase()}</small><Link to={i.kind==='Evento'?`/segreta/entita/${i.id}`:`/segreta/record/${i.id}`}>{i.title}</Link><code>{i.id}</code></div></div>)}</div></div>}
